/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;
import utils.DatabaseService;
import utils.Notify;

/**
 *
 * @author hexademical
 */
public class AddNewProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProduct
     */
    public AddNewProduct() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newProductNameTextField = new javax.swing.JTextField();
        newProductPriceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newProductTotalTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newProductDescriptionTextArea = new javax.swing.JTextArea();
        addNewProductButton = new javax.swing.JButton();
        cancelAddProductButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setText("Add Product");

        jLabel2.setFont(new java.awt.Font("Noto Sans Thai", 0, 18)); // NOI18N
        jLabel2.setText("เพิ่มสินค้าใหม่");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Name :");

        newProductNameTextField.setFont(new java.awt.Font("Noto Sans Thai", 0, 12)); // NOI18N
        newProductNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductNameTextFieldActionPerformed(evt);
            }
        });

        newProductPriceTextField.setFont(new java.awt.Font("Noto Sans Thai", 0, 12)); // NOI18N
        newProductPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductPriceTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Price :");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Total :");

        newProductTotalTextField.setFont(new java.awt.Font("Noto Sans Thai", 0, 12)); // NOI18N
        newProductTotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductTotalTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Description :");

        newProductDescriptionTextArea.setColumns(20);
        newProductDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(newProductDescriptionTextArea);

        addNewProductButton.setBackground(new java.awt.Color(61, 127, 161));
        addNewProductButton.setFont(new java.awt.Font("Noto Sans Thai", 0, 14)); // NOI18N
        addNewProductButton.setText("เพิ่ม");
        addNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProductButtonActionPerformed(evt);
            }
        });

        cancelAddProductButton.setFont(new java.awt.Font("Noto Sans Thai", 0, 14)); // NOI18N
        cancelAddProductButton.setText("ยกเลิก");
        cancelAddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addNewProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelAddProductButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(newProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newProductTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newProductPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel6)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newProductPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newProductTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAddProductButton)
                    .addComponent(addNewProductButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newProductNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductNameTextFieldActionPerformed

    private void newProductPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductPriceTextFieldActionPerformed

    private void newProductTotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductTotalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductTotalTextFieldActionPerformed

    private void cancelAddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddProductButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelAddProductButtonActionPerformed

    private boolean validateProductData() {
        String productName = newProductNameTextField.getText();
        String productPriceStr = newProductPriceTextField.getText();
        String productTotalStr = newProductTotalTextField.getText();
        String productDescription = newProductDescriptionTextArea.getText();

        // Validate productName is not empty
        if (productName.isEmpty()) {
            // แจ้งเตือนเมื่อชื่อสินค้าว่าง
            Notify.showNotify(this, "ข้อผิดพลาด", "กรุณากรอกชื่อสินค้า", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate productPrice is a valid double
        try {
            double productPrice = Double.parseDouble(productPriceStr);
        } catch (NumberFormatException e) {
            // แจ้งเตือนเมื่อราคาสินค้าไม่ถูกต้อง
            Notify.showNotify(this, "ข้อผิดพลาด", "กรุณากรอกราคาที่ถูกต้อง", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate productTotal is a valid integer
        try {
            int productTotal = Integer.parseInt(productTotalStr);
        } catch (NumberFormatException e) {
            // แจ้งเตือนเมื่อจำนวนสินค้าที่มีให้ไม่ถูกต้อง
            Notify.showNotify(this, "ข้อผิดพลาด", "กรุณากรอกจำนวนสินค้าที่มีให้ให้ถูกต้อง", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate productDescription is not empty
        if (productDescription.isEmpty()) {
            // แจ้งเตือนเมื่อคำอธิบายสินค้าว่าง
            Notify.showNotify(this, "ข้อผิดพลาด", "กรุณากรอกคำอธิบายสินค้า", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // ข้อมูลทั้งหมดถูกต้อง
        return true;
    }


    private void addNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProductButtonActionPerformed
        if (!validateProductData()) {
            return;
        }

        String productName = newProductNameTextField.getText();
        String productDescription = newProductDescriptionTextArea.getText();
        double productPrice = Double.parseDouble(newProductPriceTextField.getText());
        int productTotal = Integer.parseInt(newProductTotalTextField.getText());

        // Create new Product instance
        Product newProduct = new Product();
        newProduct.setName(productName);
        newProduct.setDescription(productDescription);
        newProduct.setPrice(productPrice);
        newProduct.setTotalAvailable(productTotal);

        // ปุ่มยืนยันการเพิ่มสินค้าใหม่ พร้อมข้อมูลที่กรอกเข้าไป
        if (Notify.confirmOption(this, "ยืนยันการเพิ่มสินค้าใหม่", "คุณต้องการเพิ่มสินค้า " + newProduct.getName() + " ใหม่ใช่หรือไม่?")) {
            // แจ้งเตือนเมื่อสินค้าถูกเพิ่มเข้าไปในฐานข้อมูล
            if (DatabaseService.getInstance().addNewProduct(newProduct) == 1) {
                Notify.showNotify(this, "สำเร็จ", "เพิ่มสินค้าใหม่เรียบร้อยแล้ว", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_addNewProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddNewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewProductButton;
    private javax.swing.JButton cancelAddProductButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea newProductDescriptionTextArea;
    private javax.swing.JTextField newProductNameTextField;
    private javax.swing.JTextField newProductPriceTextField;
    private javax.swing.JTextField newProductTotalTextField;
    // End of variables declaration//GEN-END:variables
}
