/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import data.GlobalData;
import javax.swing.JOptionPane;
import utils.DatabaseService;
import utils.Notify;

/**
 *
 * @author hexademical
 */
public class DatabaseApplication extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseApplication
     */
    public DatabaseApplication() {
        initComponents();
    }

    private String getEmail() {
        return emailTextField.getText();
    }

    private String getPassword() {
        char[] passwordChars = passwordTextField.getPassword();
        String password = new String(passwordChars);
        return password;
    }

    public boolean validateEmailPassword() {
        String email = getEmail();
        String password = getPassword();
        return !(email.isEmpty() || password.isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpWindows = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        jlEngTitle = new javax.swing.JLabel();
        jlThaiTitle = new javax.swing.JLabel();
        jlLicense = new javax.swing.JLabel();
        jlThaiTitle1 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jlThaiTitle2 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple POS Database Management");
        setBackground(new java.awt.Color(26, 35, 39));
        setFont(new java.awt.Font("Noto Sans Thai", 0, 12)); // NOI18N
        setIconImages(null);
        setLocation(new java.awt.Point(50, 50));
        setName("application"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpWindows.setBackground(new java.awt.Color(26, 35, 39));
        tpWindows.setForeground(new java.awt.Color(255, 255, 255));
        tpWindows.setToolTipText("");
        tpWindows.setFocusable(false);
        tpWindows.setFont(new java.awt.Font("Noto Sans Thai", 0, 12)); // NOI18N
        tpWindows.setMaximumSize(new java.awt.Dimension(800, 600));
        tpWindows.setMinimumSize(new java.awt.Dimension(800, 600));
        tpWindows.setPreferredSize(new java.awt.Dimension(800, 600));

        panelLogin.setBackground(new java.awt.Color(26, 35, 39));
        panelLogin.setForeground(new java.awt.Color(255, 255, 255));
        panelLogin.setFont(new java.awt.Font("Noto Sans Thai", 0, 12)); // NOI18N
        panelLogin.setMaximumSize(new java.awt.Dimension(800, 600));
        panelLogin.setMinimumSize(new java.awt.Dimension(800, 600));
        panelLogin.setPreferredSize(new java.awt.Dimension(800, 600));

        jlEngTitle.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jlEngTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlEngTitle.setText("SIMPLE POS DATABASE MANAGEMENT");

        jlThaiTitle.setFont(new java.awt.Font("Noto Sans Thai", 0, 14)); // NOI18N
        jlThaiTitle.setForeground(new java.awt.Color(201, 209, 217));
        jlThaiTitle.setText("จัดการฐานข้อมูลร้านขายของทั่วไป");

        jlLicense.setFont(new java.awt.Font("Noto Sans Thai", 0, 10)); // NOI18N
        jlLicense.setForeground(new java.awt.Color(201, 209, 217));
        jlLicense.setText("Develop by 62160246, 62160242 BUU Students");

        jlThaiTitle1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jlThaiTitle1.setForeground(new java.awt.Color(255, 255, 255));
        jlThaiTitle1.setText("Email");

        emailTextField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        emailTextField.setActionCommand("<Not Set>");
        emailTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        emailTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        jlThaiTitle2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jlThaiTitle2.setForeground(new java.awt.Color(255, 255, 255));
        jlThaiTitle2.setText("Password");

        passwordTextField.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        passwordTextField.setPreferredSize(new java.awt.Dimension(64, 31));

        loginButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlLicense)
                .addContainerGap())
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton)
                    .addComponent(jlThaiTitle2)
                    .addComponent(jlThaiTitle1)
                    .addComponent(jlEngTitle)
                    .addComponent(jlThaiTitle)
                    .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlEngTitle)
                .addGap(0, 0, 0)
                .addComponent(jlThaiTitle)
                .addGap(93, 93, 93)
                .addComponent(jlThaiTitle1)
                .addGap(0, 0, 0)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlThaiTitle2)
                .addGap(0, 0, 0)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(jlLicense)
                .addContainerGap())
        );

        tpWindows.addTab("Login", panelLogin);

        getContentPane().add(tpWindows, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -38, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if (!validateEmailPassword()) {
            Notify.showNotify(this, "Something's went wrong!", "Please input email and password!", 0);
            return;
        }
        DatabaseService.getInstance().login(getEmail(), getPassword());
        if(!GlobalData.getInstance().isLogginned()){
            Notify.showNotify(this, "Something's went wrong!", "Not found user!", 0);
        }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jlEngTitle;
    private javax.swing.JLabel jlLicense;
    private javax.swing.JLabel jlThaiTitle;
    private javax.swing.JLabel jlThaiTitle1;
    private javax.swing.JLabel jlThaiTitle2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTabbedPane tpWindows;
    // End of variables declaration//GEN-END:variables
}
